# Generated by Django 4.1.7 on 2023-04-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=30)),
                ('campo2', models.CharField(max_length=30)),
                ('campo3', models.CharField(max_length=30)),
                ('campo4', models.CharField(max_length=30)),
                ('campo5', models.CharField(max_length=30)),
                ('campo6', models.CharField(max_length=30)),
            ],
        ),
    ]
