# Generated by Django 4.1.7 on 2023-04-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='tabla',
        ),
    ]
